---
- hosts: qaserver
  become: yes
  ignore_errors: yes
   tasks:
     - name: install package
       package:
           name: "{{ item }}"
           state: present
       with_items:
            - unzip
            - wget
            - httpd
     - name: download
       shell: wget https://github.com/utrains/static-resume/archive/refs/heads/main.zip 

